#ifndef ERRORS_H
#define ERRORS_H

typedef enum
{
    ERROR_SUCCESS,
    ERROR_READING_FILE,
    ERROR_ALLOCATING_MEM,
    ERROR_INVALID_PTR,
    ERROR_OPENING_FILE,
    ERROR_READING_STRING,
    ERROR_EMPTY_STRING,
    ERROR_NOT_A_NUMBER,
    ERROR_INVALID_POINTS_COUNT,
    ERROR_INVALID_EDGES_COUNT,
    ERROR_INVALID_EDGE
} err_code_e;

void handleError(err_code_e rc);

#endif /* ERRORS_H */
